# Generated by Django 4.2.7 on 2026-09-11 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, help_text='Why support was needed')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to='companies.company')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rono_support_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', '-started_at'], name='rono_suppor_company_a0e5d0_idx'), models.Index(fields=['super_admin', '-started_at'], name='rono_suppor_super_a_e4f69d_idx')],
            },
        ),
    ]
