# Generated by Django 4.2.7 on 2026-09-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_add_mpesa_integration'),
        ('companies', '0002_supportsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscription_start',
        ),
        migrations.AddField(
            model_name='company',
            name='plan_fk',
            field=models.ForeignKey(blank=True, help_text='Current plan (synced from active subscription)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
