# Generated by Django 4.2.7 on 2026-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_plan_fk_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., clientcompany.co.ke (no https:// or trailing slash)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='domain_verified',
            field=models.BooleanField(default=False, help_text='Set to True after DNS is confirmed working'),
        ),
    ]
