# Generated by Django 4.2.7 on 2026-09-15 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0007_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('requested_role', models.CharField(default='company_staff', max_length=20)),
                ('assigned_role', models.CharField(blank=True, default='', help_text='Role that was actually assigned when this request was approved.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_branch', models.ForeignKey(blank=True, help_text='Branch chosen at approval time (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request_assigned', to='epa_shop.branch')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='The User account created when this request was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rono_company_join_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='rono_compan_company_6b788c_idx'), models.Index(fields=['status', '-created_at'], name='rono_compan_status_55a347_idx')],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
