# Generated by Django 4.2.7 on 2026-09-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated unique company ID (e.g. F@RS001). Employees use this to register into the company.', max_length=20, unique=True),
        ),
    ]
