# Generated by Django 4.2.7 on 2026-09-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('companies', '0009_companyjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyjoinrequest',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='Branch chosen at approval time (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request_assigned', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='companyjoinrequest',
            name='assigned_role',
            field=models.CharField(blank=True, default='', help_text='Role that was actually assigned when this request was approved.', max_length=20),
        ),
        migrations.AddField(
            model_name='companyjoinrequest',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='The User account created when this request was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
