# Generated by Django 6.1.1 on 2026-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='name',
            field=models.CharField(choices=[('EPA Shop', 'EPA Shop'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail'), ('Restaurant', 'Restaurant'), ('Supermarket', 'Supermarket'), ('Kuku Biz', 'Kuku Biz')], max_length=100, unique=True),
        ),
    ]
