# Generated by Django 6.1.1 on 2026-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        ('company', '0005_alter_expense_attachment_branch_alter_expense_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjoinrequest',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, help_text='Branch chosen at approval time (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_request_assigned', to='company.branch'),
        ),
    ]
