# Generated by Django 6.1.1 on 2026-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyjoinrequest_assigned_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accent_color',
            field=models.CharField(default='#036a77', help_text='Hex color used for the sidebar and secondary UI accents.', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='favicon',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public_id for the company favicon (e.g. companies/42/favicon_1789754321).', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#87CEEB', help_text='Hex color used for primary UI accents.', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='system_name',
            field=models.CharField(blank=True, help_text='Display name override for the sidebar and page titles (defaults to `name` if blank).', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., clientcompany.co.ke (no https://, no www., no trailing slash)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public_id for the company logo (e.g. companies/42/logo_1789754321).', max_length=255),
        ),
    ]
