# Generated by Django 6.1.1 on 2026-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_accent_color_company_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='login_background',
            field=models.CharField(blank=True, default='', help_text="Cloudinary public_id for the login page background (e.g. companies/42/login_background_1789754321). Only shown when the user is on this company's domain.", max_length=255),
        ),
    ]
