# Generated by Django 6.1.1 on 2026-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_login_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='receipt_logo',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public_id for the receipt/ETR logo (e.g. companies/42/receipt_logo_1789754321). If empty, the main `logo` is used on receipts.', max_length=255),
        ),
    ]
