# Generated by Django 6.1.1 on 2026-10-02 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_receipt_logo'),
        ('company', '0009_expense_paid_by_expense_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug / Error'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low — minor annoyance'), ('normal', 'Normal — should fix soon'), ('high', 'High — blocking my work'), ('critical', 'Critical — losing data / money')], default='normal', max_length=20)),
                ('title', models.CharField(help_text="Short summary — e.g. 'Cannot upload PDF receipts'", max_length=200)),
                ('message', models.TextField(help_text='Full description of the issue or request')),
                ('page_url', models.CharField(blank=True, help_text='Where the user was when the feedback was submitted', max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('screenshot', models.FileField(blank=True, help_text='Cloudinary public_id for the screenshot (optional)', max_length=500, null=True, upload_to='tenant_feedback/%Y/%m/')),
                ('screenshot_format', models.CharField(blank=True, default='', help_text='Cloudinary format (jpg, png, pdf, ...).', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('wont_fix', "Won't Fix")], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — not shown to the tenant.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch the user was on when submitting (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='companies.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_resolved', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rono_tenant_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='rono_tenant_company_de359d_idx'), models.Index(fields=['status', '-created_at'], name='rono_tenant_status_b74916_idx'), models.Index(fields=['feedback_type', 'status'], name='rono_tenant_feedbac_b1d07c_idx')],
            },
        ),
    ]
