# Generated by Django 6.1.1 on 2026-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_tenantfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pin',
            field=models.CharField(blank=True, default='', help_text='KRA PIN / Tax identification number shown on receipts.', max_length=20),
        ),
    ]
