# Generated by Django 4.2.7 on 2026-08-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('epa_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique product code within the company (auto-generated)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique product code within the company (auto-generated)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique product code within the company (auto-generated)', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='accessory',
            unique_together={('company', 'product_code')},
        ),
    ]
