# Generated by Django 4.2.7 on 2026-08-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0002_alter_accessory_product_code_and_more'),
        ('epa_shop', '0003_fix_duplicate_product_codes'),
    ]

    operations = [
    ]
