# Generated by Django 4.2.7 on 2026-08-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0004_merge_20260828_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='epa_shop.branch'),
        ),
    ]
