# Generated by Django 4.2.7 on 2026-08-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0005_alter_stockmovement_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_keen_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Next of Keen Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_keen_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Next of Keen Phone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id_number'], name='epa_custome_id_numb_263f04_idx'),
        ),
    ]
