# Generated by Django 4.2.7 on 2026-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0006_customer_id_number_customer_next_of_keen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone'], name='epa_custome_company_ae3fca_idx'),
        ),
    ]
