# Generated by Django 4.2.7 on 2026-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0008_sale_company_sale_id_sale_sale_number_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='epa_sales_company_34ecab_idx',
            old_name='epa_sales_company_sale_number_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='epa_sales_company_83a78f_idx',
            old_name='epa_sales_company_sale_id_idx',
        ),
        migrations.AlterField(
            model_name='sale',
            name='company_sale_id',
            field=models.CharField(blank=True, editable=False, help_text='Company prefix + sale number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Sequential number per company'),
        ),
    ]
