# Generated by Django 4.2.7 on 2026-09-03 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epa_shop', '0009_rename_epa_sales_company_sale_number_idx_epa_sales_company_34ecab_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_code', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('main', 'Main COGS Account'), ('branch', 'Branch COGS Account'), ('product', 'Product Category Account')], default='main', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credited', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_debited', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_accounts', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_accounts', to='companies.company')),
            ],
            options={
                'db_table': 'finance_cogs_accounts',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='COGSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (From Sales)'), ('debit', 'Debit (Used for Purchases)'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_transactions', to='epa_shop.branch')),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='epa_shop.cogsaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_transactions', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_transactions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_transactions', to='epa_shop.sale')),
            ],
            options={
                'db_table': 'finance_cogs_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='COGSSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_summaries', to='epa_shop.branch')),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='epa_shop.cogsaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_summaries', to='companies.company')),
            ],
            options={
                'db_table': 'finance_cogs_summaries',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='COGSAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('electronics_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('phones_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('accessories_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessories_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories_rules', to='epa_shop.cogsaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_rules', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_rules', to='companies.company')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_rules', to='epa_shop.cogsaccount')),
                ('electronics_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronics_rules', to='epa_shop.cogsaccount')),
                ('phones_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones_rules', to='epa_shop.cogsaccount')),
            ],
            options={
                'db_table': 'finance_cogs_allocation_rules',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=50, unique=True)),
                ('purchase_type', models.CharField(choices=[('inventory', 'Inventory Purchase'), ('supplies', 'Supplies'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_contact', models.CharField(blank=True, max_length=100)),
                ('supplier_phone', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('m-pesa', 'M-Pesa'), ('cheque', 'Cheque'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='finance/purchases/%Y/%m/')),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='epa_shop.branch')),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='epa_shop.cogsaccount')),
                ('cogs_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_record', to='epa_shop.cogstransaction')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_purchase_records',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['company', 'purchase_date'], name='finance_pur_company_054619_idx'), models.Index(fields=['branch', 'purchase_date'], name='finance_pur_branch__b6f1bc_idx'), models.Index(fields=['status'], name='finance_pur_status_ccecd0_idx'), models.Index(fields=['purchase_number'], name='finance_pur_purchas_71be6e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cogstransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='finance_cog_company_8daba3_idx'),
        ),
        migrations.AddIndex(
            model_name='cogstransaction',
            index=models.Index(fields=['cogs_account', 'transaction_date'], name='finance_cog_cogs_ac_109d38_idx'),
        ),
        migrations.AddIndex(
            model_name='cogstransaction',
            index=models.Index(fields=['transaction_type'], name='finance_cog_transac_396928_idx'),
        ),
        migrations.AddIndex(
            model_name='cogstransaction',
            index=models.Index(fields=['sale'], name='finance_cog_sale_id_ceb846_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cogssummary',
            unique_together={('company', 'cogs_account', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='cogsaccount',
            index=models.Index(fields=['company', 'is_active'], name='finance_cog_company_bf700d_idx'),
        ),
        migrations.AddIndex(
            model_name='cogsaccount',
            index=models.Index(fields=['branch', 'is_active'], name='finance_cog_branch__426e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='cogsaccount',
            index=models.Index(fields=['account_code'], name='finance_cog_account_a7811c_idx'),
        ),
    ]
