# Generated by Django 4.2.7 on 2026-09-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0010_cogsaccount_cogstransaction_cogssummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='epa_shop.cogsaccount'),
        ),
    ]
