# Generated by Django 4.2.7 on 2026-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0011_alter_purchaserecord_cogs_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='accessory_type',
            field=models.CharField(choices=[('electronic accessory', 'Electronic Accessory'), ('phone accessory', 'Phone Accessory')], max_length=20),
        ),
    ]
