# Generated by Django 4.2.7 on 2026-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0012_alter_accessory_accessory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='features',
            field=models.TextField(blank=True, help_text='Feature phone features like FM Radio, Torch, etc.', null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory_card',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='network_type',
            field=models.CharField(blank=True, choices=[('2g', '2G'), ('3g', '3G'), ('4g', '4G'), ('dual_sim', 'Dual SIM')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('feature', 'Feature Phone')], default='smartphone', max_length=20),
        ),
    ]
