# Generated by Django 4.2.7 on 2026-09-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0013_phone_features_phone_memory_card_phone_network_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='best_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronic',
            name='best_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='best_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
