# Generated by Django 4.2.7 on 2026-09-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0014_accessory_best_price_electronic_best_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='best_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='best_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='maximum_stock_level',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='minimum_stock_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='phone',
            name='best_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='maximum_stock_level',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='minimum_stock_level',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
