# Generated by Django 6.1.1 on 2026-09-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='epa/accessories/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='epa/electronics/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='epa/phones/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Cloudinary public_id (URL built via receipt_image_url property)', max_length=500, null=True, upload_to='finance/purchases/%Y/%m/'),
        ),
    ]
