# Generated by Django 6.1.1 on 2026-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_branch'),
        ('companies', '0011_alter_companyjoinrequest_assigned_branch'),
        ('company', '0005_alter_expense_attachment_branch_alter_expense_branch'),
        ('epa_shop', '0016_alter_accessory_image_alter_electronic_image_and_more'),
        ('kuku_biz', '0015_alter_birdsale_branch_alter_eggproduction_branch_and_more'),
        ('treasury', '0004_alter_bankaccount_branch_alter_dailyrecord_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogsaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_accounts', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='cogstransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_transactions', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='cogssummary',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_summaries', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='cogsallocationrule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_rules', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='company.branch'),
        ),
        # Branch moved to the 'company' app. The table ("epa_branches")
        # stays in place — only remove the model from this app's state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Branch'),
            ],
            database_operations=[],
        ),
    ]