# Generated by Django 6.1.1 on 2026-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_company_pin'),
        ('company', '0009_expense_paid_by_expense_updated_by'),
        ('epa_shop', '0017_alter_cogsaccount_branch_alter_electronic_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode/UPC/EAN for scanner lookup', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electronic',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode/UPC/EAN for scanner lookup', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode/UPC/EAN for scanner lookup', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['company', 'barcode'], name='epa_accesso_company_50904b_idx'),
        ),
        migrations.AddIndex(
            model_name='electronic',
            index=models.Index(fields=['company', 'barcode'], name='epa_electro_company_47ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['company', 'barcode'], name='epa_phones_company_7af79a_idx'),
        ),
    ]
