# Generated by Django 6.1.1 on 2026-10-09 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_company_pin'),
        ('company', '0009_expense_paid_by_expense_updated_by'),
        ('epa_shop', '0018_accessory_barcode_electronic_barcode_phone_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='barcode_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated scannable barcode (BAR-YYYYMMDD-XXXXXX)', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['barcode_number'], name='epa_sales_barcode_2b05fb_idx'),
        ),
    ]
