# Generated by Django 4.2.7 on 2026-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_custom_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_branches',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_employees',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'FREE'), ('basic', 'BASIC'), ('premium', 'PREMIUM'), ('standard', 'STANDARD'), ('enterprise', 'ENTERPRISE')], max_length=50, unique=True),
        ),
    ]
