# Generated by Django 4.2.7 on 2026-08-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_add_max_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_mpesa_intergration',
            field=models.BooleanField(default=False),
        ),
    ]
