# Generated by Django 6.1.1 on 2026-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_add_mpesa_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_treasury',
            field=models.BooleanField(default=False),
        ),
    ]
