# Generated by Django 6.1.1 on 2026-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_has_treasury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'FREE'), ('free_trial', 'FREE TRIAL'), ('basic', 'BASIC'), ('basic_pro', 'BASIC PRO'), ('premium', 'PREMIUM'), ('premium_pro', 'PREMIUM PRO'), ('standard', 'STANDARD'), ('standard_pro', 'STANDARD PRO'), ('enterprise', 'ENTERPRISE'), ('enterprise_pro', 'ENTERPRISE PRO')], max_length=50, unique=True),
        ),
    ]
