# Generated by Django 6.1.1 on 2026-10-06 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_tenantfeedback'),
        ('plans', '0005_alter_plan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_message',
            field=models.TextField(blank=True, default='', help_text='M-Pesa / bank confirmation message pasted by the customer.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_receipt',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public_id of the uploaded receipt.', max_length=500),
        ),
        migrations.AddField(
            model_name='subscription',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='Optional note from the reviewer (reason for rejection, etc.).'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'payment_method'], name='subscriptio_status_4943df_idx'),
        ),
    ]
