# Generated by Django 6.1.1 on 2026-10-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_rename_mpesa_integration_typo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='has_mpesa_intergration',
            new_name='has_mpesa_integration',
        ),
    ]
