# Generated by Django 4.2.7 on 2026-09-06 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epa_shop', '0013_phone_features_phone_memory_card_phone_network_type_and_more'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_type', models.CharField(choices=[('EQUITY', 'Equity Bank'), ('KCB', 'KCB Bank'), ('COOP', 'Co-operative Bank'), ('ABSA', 'ABSA Bank'), ('STANBIC', 'Stanbic Bank'), ('SC', 'Standard Chartered'), ('NCBA', 'NCBA Bank'), ('DTB', 'Diamond Trust Bank'), ('FAMILY', 'Family Bank'), ('GUARDIAN', 'Guardian Bank'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('account_name', models.CharField(help_text='Enter bank account name (e.g., KCB A, KCB B, ABSA A)', max_length=200)),
                ('account_number', models.CharField(help_text='Enter bank account number', max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current/Last recorded balance for this account', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'bank_type', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bank_balance', models.DecimalField(decimal_places=2, default=0, help_text='Total of all bank accounts', max_digits=15)),
                ('total_mpesa_balance', models.DecimalField(decimal_places=2, default=0, help_text='Total of all M-Pesa accounts', max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, help_text='Physical Cash in Shop', max_digits=12)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, help_text='Money owed to you / Credit float', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasury', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasuries', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Treasuries',
                'ordering': ['company', 'branch__name'],
                'unique_together': {('company', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('till_name', models.CharField(help_text='Enter M-Pesa Till/Account name (e.g., MPESA A, MPESA B)', max_length=200)),
                ('till_number', models.CharField(help_text='Enter M-Pesa Till number', max_length=20)),
                ('store_number', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till Number'), ('SEND_MONEY', 'Send Money')], default='TILL', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current/Last recorded balance for this M-Pesa account', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='companies.company')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='treasury.treasury')),
            ],
            options={
                'ordering': ['company', 'till_name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('BOOST', 'BOOST - External Money Injection'), ('TRANSFER', 'Transfer between accounts'), ('ADJUSTMENT', 'Manual Adjustment')], default='TRANSFER', max_length=20)),
                ('from_account', models.CharField(choices=[('BANK', 'Bank'), ('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('CREDIT', 'Credit'), ('EXTERNAL', 'External (BOOST)')], max_length=20)),
                ('to_account', models.CharField(choices=[('BANK', 'Bank'), ('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('CREDIT', 'Credit'), ('EXTERNAL', 'External (BOOST)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('boost_source', models.CharField(blank=True, choices=[('PERSONAL_SAVINGS', 'Personal Savings'), ('COMMISSIONS', 'M-Pesa Commissions'), ('INVESTOR_FUNDS', 'Investor Funds'), ('BANK_LOAN', 'Bank Loan'), ('BUSINESS_PARTNER', 'Business Partner'), ('PROFIT_REINVESTMENT', 'Profit Reinvestment'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('boost_reference', models.CharField(blank=True, max_length=100)),
                ('boost_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_movements', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_movements', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements', to=settings.AUTH_USER_MODEL)),
                ('from_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='treasury.bankaccount')),
                ('from_mpesa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='treasury.mpesaaccount')),
                ('to_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='treasury.bankaccount')),
                ('to_mpesa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='treasury.mpesaaccount')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='treasury.treasury')),
            ],
            options={
                'ordering': ['company', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, help_text='Physical cash in shop', max_digits=15)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, help_text='Money owed to you / Credit float', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='companies.company')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='treasury.treasury')),
            ],
            options={
                'ordering': ['company', 'branch', '-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyMpesaBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Closing balance for this M-Pesa account', max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_balances', to='treasury.dailyrecord')),
                ('mpesa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='treasury.mpesaaccount')),
            ],
            options={
                'ordering': ['mpesa_account__till_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyBankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, help_text='Closing balance for this bank account', max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='treasury.bankaccount')),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balances', to='treasury.dailyrecord')),
            ],
            options={
                'ordering': ['bank_account__bank_type', 'bank_account__account_name'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='treasury.treasury'),
        ),
        migrations.CreateModel(
            name='TreasuryTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('daily_record', 'Daily Record Update'), ('movement', 'Account Movement'), ('boost', 'BOOST Injection'), ('manual_adjustment', 'Manual Adjustment'), ('sale', 'Sale'), ('expense', 'Expense'), ('purchase', 'Purchase')], max_length=20)),
                ('bank_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mpesa_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_logs', to='companies.company')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_logs', to=settings.AUTH_USER_MODEL)),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='treasury.treasury')),
            ],
            options={
                'ordering': ['company', '-created_at'],
                'indexes': [models.Index(fields=['company', 'treasury', 'created_at'], name='treasury_tr_company_de54fc_idx'), models.Index(fields=['company', 'transaction_type'], name='treasury_tr_company_0eb2d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TreasurySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('opening_net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_boost_in', models.DecimalField(decimal_places=2, default=0, help_text='Total BOOST injections', max_digits=15)),
                ('total_movements_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_movements_out', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('boost_count', models.IntegerField(default=0)),
                ('transfer_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_summaries', to='companies.company')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='treasury.treasury')),
            ],
            options={
                'verbose_name_plural': 'Treasury Summaries',
                'ordering': ['company', '-month'],
                'unique_together': {('company', 'treasury', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='treasury_mp_company_a5a581_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesaaccount',
            index=models.Index(fields=['till_number'], name='treasury_mp_till_nu_817faf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mpesaaccount',
            unique_together={('company', 'branch', 'till_name', 'till_number')},
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='treasury_mo_company_aba343_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['company', 'movement_type'], name='treasury_mo_company_3def6f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['company', 'branch', 'date'], name='treasury_da_company_ace04a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['company', 'date'], name='treasury_da_company_7465ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('company', 'branch', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailympesabalance',
            unique_together={('daily_record', 'mpesa_account')},
        ),
        migrations.AlterUniqueTogether(
            name='dailybankbalance',
            unique_together={('daily_record', 'bank_account')},
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='treasury_ba_company_9ad0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number'], name='treasury_ba_account_e83fa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'branch', 'account_name', 'account_number')},
        ),
    ]
