# Generated by Django 4.2.7 on 2026-09-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this daily record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['created_by'], name='treasury_da_created_a70336_idx'),
        ),
    ]
