# Generated by Django 4.2.7 on 2026-09-13 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0002_dailyrecord_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the record was approved', null=True),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Set to True by company admin to lock the record.'),
        ),
    ]
