# Generated by Django 6.1.1 on 2026-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_expense_attachment_branch_alter_expense_branch'),
        ('treasury', '0003_dailyrecord_approved_at_dailyrecord_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_movements', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='mpesaaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasury', to='company.branch'),
        ),
    ]
