# Generated by Django 6.1.1 on 2026-09-30 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_receipt_logo'),
        ('company', '0007_branch_parent'),
        ('treasury', '0004_alter_bankaccount_branch_alter_dailyrecord_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month the commission is for')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Commission amount received from M-Pesa', max_digits=15)),
                ('reference', models.CharField(blank=True, help_text='Optional M-Pesa transaction/reference code', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_commissions', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_commissions', to='companies.company')),
                ('mpesa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='treasury.mpesaaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_commissions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Commission',
                'verbose_name_plural': 'M-Pesa Commissions',
                'ordering': ['company', 'branch', '-month'],
                'indexes': [models.Index(fields=['company', 'branch', 'month'], name='treasury_mp_company_336956_idx')],
                'unique_together': {('company', 'branch', 'month')},
            },
        ),
    ]
