# Generated by Django 6.1.1 on 2026-09-20 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('retail', 'Retail Shop'), ('hotel', 'Hotel / Restaurant'), ('wholesale', 'Wholesaler'), ('institution', 'Institution (School, Hospital)')], default='individual', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_customers', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('credit', 'On Credit'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='cash, mpesa, bank, credit', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_egg_sales', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_sales', to='kuku_biz.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_egg_sales_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egg Sale',
                'verbose_name_plural': 'Egg Sales',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EggSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('egg', 'Individual Egg'), ('tray', 'Tray (30 eggs)'), ('crate', 'Crate (360 eggs)')], default='tray', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kuku_biz.eggsale')),
            ],
            options={
                'verbose_name': 'Egg Sale Item',
                'verbose_name_plural': 'Egg Sale Items',
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('protein_percent', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 18.00 for 18% protein', max_digits=5, null=True)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_feed_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'Feed Type',
                'verbose_name_plural': 'Feed Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flock_type', models.CharField(choices=[('layer', 'Layers (Egg Production)'), ('broiler', 'Broilers (Meat Production)'), ('mixed', 'Mixed')], default='layer', max_length=20)),
                ('breed', models.CharField(blank=True, help_text='e.g. Isa Brown, Kuroiler, Kenbro', max_length=100)),
                ('date_acquired', models.DateField(default=django.utils.timezone.now)),
                ('initial_count', models.PositiveIntegerField(default=0)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('sold', 'Sold'), ('depleted', 'Depleted')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_flocks', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_flocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flock',
                'verbose_name_plural': 'Flocks',
                'ordering': ['-date_acquired', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_feed_records', to='companies.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_recorded', to=settings.AUTH_USER_MODEL)),
                ('feed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='kuku_biz.feedtype')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='kuku_biz.flock')),
            ],
            options={
                'verbose_name': 'Feed Record',
                'verbose_name_plural': 'Feed Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('labour', 'Labour'), ('utilities', 'Utilities'), ('equipment', 'Equipment'), ('transport', 'Transport'), ('veterinary', 'Veterinary'), ('chicks', 'Chick Purchase'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_to', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_expenses', to='companies.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(blank=True, help_text='Optional — leave blank for general farm expenses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='kuku_biz.flock')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('deworming', 'Deworming'), ('vitamin', 'Vitamin / Supplement'), ('vet_visit', 'Vet Visit'), ('other', 'Other')], default='vaccination', max_length=20)),
                ('product_used', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('administered_by', models.CharField(blank=True, max_length=150)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_health_records', to='companies.company')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='kuku_biz.flock')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_health_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('egg_tray', 'Egg Tray'), ('egg_crate', 'Egg Crate'), ('feed_bag', 'Feed Bag'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, help_text='pcs, kg, bags, etc.', max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when quantity falls below this', max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_inventory', to='companies.company')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
                ('cause', models.CharField(choices=[('disease', 'Disease'), ('predator', 'Predator'), ('culled', 'Culled'), ('accident', 'Accident'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_mortality', to='companies.company')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='kuku_biz.flock')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_mortality_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mortality Record',
                'verbose_name_plural': 'Mortality Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('egg', 'Individual Egg'), ('tray', 'Tray (30 eggs)'), ('crate', 'Crate (360 eggs)')], default='tray', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_price_history', to='companies.company')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('eggs_collected', models.PositiveIntegerField(default=0)),
                ('eggs_cracked', models.PositiveIntegerField(default=0)),
                ('eggs_broken', models.PositiveIntegerField(default=0)),
                ('eggs_consumed', models.PositiveIntegerField(default=0, help_text='Kept for home/farm use')),
                ('eggs_discarded', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_egg_production', to='companies.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_egg_records', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_production', to='kuku_biz.flock')),
            ],
            options={
                'verbose_name': 'Egg Production',
                'verbose_name_plural': 'Egg Production',
                'ordering': ['-date', 'flock__name'],
                'unique_together': {('flock', 'date')},
            },
        ),
    ]
