# Generated by Django 6.1.1 on 2026-09-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('kuku_biz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot holds this stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_inventory', to='epa_shop.branch'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, help_text='pcs, kg, bags, trays, etc.', max_length=20),
        ),
    ]
