# Generated by Django 6.1.1 on 2026-09-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('kuku_biz', '0002_inventoryitem_branch_alter_inventoryitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggproduction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch produced these eggs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_egg_production', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='eggsale',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot made this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_egg_sales', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot incurred this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_expenses', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot used this feed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_records', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='flock',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/farm houses this flock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_flocks', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot recorded this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_health_records', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='mortality',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot recorded this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_mortality', to='epa_shop.branch'),
        ),
    ]
