# Generated by Django 6.1.1 on 2026-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0003_eggproduction_branch_eggsale_branch_expense_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo of the item', null=True, upload_to='kuku/inventory/'),
        ),
    ]
