# Generated by Django 6.1.1 on 2026-09-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0004_inventoryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Cloudinary public_id (URL built via image_url property)', max_length=500, null=True, upload_to='kuku/inventory/'),
        ),
    ]
