# Generated by Django 6.1.1 on 2026-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0005_alter_inventoryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='image',
            field=models.ImageField(blank=True, help_text='Cloudinary public_id (URL built via image_url property)', max_length=500, null=True, upload_to='kuku/prices/'),
        ),
    ]
