# Generated by Django 6.1.1 on 2026-09-21 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('kuku_biz', '0006_pricehistory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsale',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='eggsale',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('company', 'invoice_number'), name='unique_invoice_per_company'),
        ),
    ]
