# Generated by Django 6.1.1 on 2026-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0007_alter_eggsale_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsaleitem',
            name='tray_size',
            field=models.PositiveIntegerField(default=30, help_text="For tray sales: 6, 12, 30, or 45. Ignored for 'egg'/'crate'."),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tray_size',
            field=models.PositiveIntegerField(choices=[(0, '— Not an egg container —'), (1, '1-Egg (Individual)'), (6, '6-Egg Tray'), (12, '12-Egg Tray'), (30, '30-Egg Tray'), (45, '45-Egg Tray'), (360, '360-Egg Crate')], default=0, help_text='Eggs per unit for egg containers. 0 for non-egg items.'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='tray_size',
            field=models.PositiveIntegerField(choices=[(0, '— Not an egg container —'), (1, '1-Egg (Individual)'), (6, '6-Egg Tray'), (12, '12-Egg Tray'), (30, '30-Egg Tray'), (45, '45-Egg Tray'), (360, '360-Egg Crate')], default=0, help_text='Which tray size this price applies to (0 for non-tray units)'),
        ),
        migrations.AlterField(
            model_name='eggsaleitem',
            name='unit',
            field=models.CharField(choices=[('egg', 'Individual Egg'), ('tray', 'Tray'), ('crate', 'Crate (360 eggs)')], default='tray', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='unit',
            field=models.CharField(choices=[('egg', 'Individual Egg'), ('tray', 'Tray'), ('crate', 'Crate (360 eggs)')], default='tray', max_length=10),
        ),
    ]
