# Generated by Django 6.1.1 on 2026-09-21 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('kuku_biz', '0008_eggsaleitem_tray_size_inventoryitem_tray_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, help_text='Walk-in buyer name if no customer record', max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('birds_sold', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per bird', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, help_text='cash, mpesa, bank, credit', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Which branch/depot made this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_bird_sales', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_bird_sales', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, help_text='Optional — leave blank for walk-in buyers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_sales', to='kuku_biz.customer')),
                ('flock', models.ForeignKey(help_text='Which flock the birds came from', on_delete=django.db.models.deletion.CASCADE, related_name='bird_sales', to='kuku_biz.flock')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_bird_sales_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bird Sale',
                'verbose_name_plural': 'Bird Sales',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
