# Generated by Django 6.1.1 on 2026-09-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0009_birdsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='age_at_acquisition_days',
            field=models.PositiveIntegerField(default=0, help_text='How old the birds were when acquired (in days)'),
        ),
        migrations.AddField(
            model_name='flock',
            name='purchase_price_per_bird',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per bird at acquisition', max_digits=10),
        ),
        migrations.AddField(
            model_name='flock',
            name='supplier',
            field=models.CharField(blank=True, help_text='Who sold the birds (hatchery, farm, supplier name)', max_length=150),
        ),
        migrations.AddField(
            model_name='flock',
            name='total_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of acquiring this flock', max_digits=12),
        ),
    ]
