# Generated by Django 6.1.1 on 2026-09-22 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('kuku_biz', '0010_flock_age_at_acquisition_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feed Consumption',
                'verbose_name_plural': 'Feed Consumption',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedrecord',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Feed Record', 'verbose_name_plural': 'Feed Records'},
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Inventory line this feed was drawn from / added to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_records', to='kuku_biz.inventoryitem'),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('credit', 'On Credit')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='record_type',
            field=models.CharField(choices=[('purchase', 'Purchase (stock in)'), ('consumption', 'Consumption (stock out)')], default='purchase', help_text='Purchase = stock in, Consumption = stock out', max_length=20),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='supplier_invoice',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='feedtype',
            name='default_unit',
            field=models.CharField(default='kg', help_text='Unit used when this feed hits inventory (kg, bag, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='feedtype',
            name='kg_per_bag',
            field=models.DecimalField(decimal_places=2, default=50, help_text="Only used when default_unit = 'bag'", max_digits=10),
        ),
        migrations.AddField(
            model_name='feedtype',
            name='stage',
            field=models.CharField(choices=[('chick', 'Chick (0–8 weeks)'), ('grower', 'Grower (9–18 weeks)'), ('layer', 'Layer (19+ weeks)'), ('broiler', 'Broiler'), ('finisher', 'Finisher'), ('other', 'Other')], default='other', help_text='Life stage this feed is designed for', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot this feed belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_records', to='epa_shop.branch'),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost (purchase only). 0 for consumption.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='flock',
            field=models.ForeignKey(blank=True, help_text='Which flock this feed is for (blank for general stock)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='kuku_biz.flock'),
        ),
        migrations.AddConstraint(
            model_name='feedtype',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'brand'), name='unique_feed_type_per_company'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_consumption', to='epa_shop.branch'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_feed_consumption', to='companies.company'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='feed_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_source', to='kuku_biz.feedrecord'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='feed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_records', to='kuku_biz.feedtype'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_consumption', to='kuku_biz.flock'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_consumption', to='kuku_biz.inventoryitem'),
        ),
        migrations.AddField(
            model_name='feedconsumption',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_consumption_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='feedconsumption',
            constraint=models.UniqueConstraint(fields=('flock', 'feed_type', 'date'), name='unique_feed_consumption_per_day'),
        ),
    ]
