# Generated by Django 6.1.1 on 2026-09-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        ('epa_shop', '0015_alter_accessory_best_price_and_more'),
        ('kuku_biz', '0011_feedconsumption_alter_feedrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Health Record', 'verbose_name_plural': 'Health Records'},
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='admin_method',
            field=models.CharField(blank=True, choices=[('drinking_water', 'Drinking water'), ('injection', 'Injection'), ('eye_drop', 'Eye drop'), ('spray', 'Spray'), ('oral', 'Oral'), ('other', 'Other')], default='drinking_water', max_length=20),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='birds_treated',
            field=models.PositiveIntegerField(default=0, help_text='How many birds received this on this date'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Inventory line this item was drawn from / added to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='kuku_biz.inventoryitem'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('credit', 'On Credit')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How many units were purchased or administered', max_digits=10),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='record_type_legacy',
            field=models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('deworming', 'Deworming'), ('vitamin', 'Vitamin / Supplement'), ('vet_visit', 'Vet Visit'), ('other', 'Other')], default='vaccination', help_text='Old field — kept to preserve existing records', max_length=20),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='supplier_invoice',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='unit',
            field=models.CharField(default='dose', help_text='dose, vial, ml, sachet, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_health_records', to='epa_shop.branch'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost (purchase only). 0 for administration.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='flock',
            field=models.ForeignKey(blank=True, help_text='Which flock received this (administration only). Blank for general stock.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='kuku_biz.flock'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Auto-suggested from vaccine_type.repeat_interval_days if left blank', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='product_used',
            field=models.CharField(blank=True, help_text='Legacy free-text product name — prefer vaccine_type now', max_length=150),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('purchase', 'Purchase (stock in)'), ('administration', 'Administration (given to birds)')], default='administration', max_length=20),
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('item_kind', models.CharField(choices=[('vaccine', 'Vaccine'), ('drug', 'Drug / Antibiotic'), ('dewormer', 'Dewormer'), ('vitamin', 'Vitamin / Supplement'), ('disinfectant', 'Disinfectant'), ('other', 'Other')], default='vaccine', max_length=20)),
                ('target_disease', models.CharField(blank=True, help_text='e.g. Newcastle, Gumboro, Fowl Typhoid', max_length=150)),
                ('default_unit', models.CharField(default='dose', help_text='Unit used when this item hits inventory', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Typical price per unit (dose, vial, ml…)', max_digits=10)),
                ('repeat_interval_days', models.PositiveIntegerField(blank=True, default=0, help_text='0 = one-off. E.g. 21 for Gumboro booster reminders.')),
                ('storage_notes', models.CharField(blank=True, help_text="e.g. 'Keep refrigerated at 2-8°C'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuku_vaccine_types', to='companies.company')),
            ],
            options={
                'verbose_name': 'Vaccine / Drug Type',
                'verbose_name_plural': 'Vaccine / Drug Types',
                'ordering': ['name', 'brand'],
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='kuku_biz.vaccinetype'),
        ),
        migrations.AddConstraint(
            model_name='vaccinetype',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'brand'), name='unique_vaccine_type_per_company'),
        ),
    ]
