# Generated by Django 6.1.1 on 2026-09-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0012_alter_healthrecord_options_healthrecord_admin_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mortality',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Mortality Record', 'verbose_name_plural': 'Mortality Records'},
        ),
        migrations.AddField(
            model_name='mortality',
            name='action_taken',
            field=models.TextField(blank=True, help_text='What was done (isolated flock, called vet, started antibiotics, etc.)'),
        ),
        migrations.AddField(
            model_name='mortality',
            name='age_group',
            field=models.CharField(choices=[('chick', 'Chick (0–8 weeks)'), ('grower', 'Grower (9–18 weeks)'), ('layer', 'Layer (19+ weeks)'), ('broiler', 'Broiler'), ('adult', 'Adult (mixed)'), ('unknown', 'Unknown')], default='unknown', help_text='Which age group the deaths occurred in', max_length=20),
        ),
        migrations.AddField(
            model_name='mortality',
            name='disposal_method',
            field=models.CharField(choices=[('buried', 'Buried'), ('burned', 'Burned / Incinerated'), ('compost', 'Composted'), ('vet_necropsy', 'Sent to Vet (Necropsy)'), ('sold', 'Sold (culled to market)'), ('consumed', 'Consumed'), ('none', 'Not recorded')], default='none', help_text='How the carcasses were handled', max_length=20),
        ),
        migrations.AddField(
            model_name='mortality',
            name='estimated_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated financial loss from these deaths', max_digits=12),
        ),
        migrations.AddField(
            model_name='mortality',
            name='related_health_record',
            field=models.ForeignKey(blank=True, help_text='Optional — link to a treatment or vaccination record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to='kuku_biz.healthrecord'),
        ),
        migrations.AddField(
            model_name='mortality',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Observable symptoms before death (e.g. 'ruffled feathers, bloody droppings')"),
        ),
    ]
