# Generated by Django 6.1.1 on 2026-09-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_biz', '0013_alter_mortality_options_mortality_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much has been paid so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('credit', 'On Credit')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, help_text='Receipt #, invoice #, M-Pesa code, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of this expense', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('transport', 'Transportation'), ('maintenance', 'Maintenance'), ('emergency', 'Emergencies'), ('labour', 'Labour Costs'), ('bills', 'Bills (Water, Power, Internet)'), ('materials', 'Materials & Supplies'), ('feed', 'Feed'), ('veterinary', 'Veterinary / Health'), ('chicks', 'Chick Purchase'), ('equipment', 'Equipment'), ('rent', 'Rent / Lease'), ('security', 'Security'), ('marketing', 'Marketing / Advertising'), ('licenses', 'Licenses & Permits'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(blank=True, help_text='Who was paid (vendor, employee, supplier)', max_length=150),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit', 'Credit (pay later)'), ('other', 'Other')], default='cash', max_length=30),
        ),
    ]
