# Generated by Django 6.1.1 on 2026-09-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_expense_attachment_branch_alter_expense_branch'),
        ('kuku_biz', '0014_alter_expense_options_expense_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsale',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot made this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_bird_sales', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='eggproduction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch produced these eggs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_egg_production', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='eggsale',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot made this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_egg_sales', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot incurred this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_expenses', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='feedconsumption',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_consumption', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot this feed belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_feed_records', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='flock',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/farm houses this flock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_flocks', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot this belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_health_records', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot holds this stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_inventory', to='company.branch'),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch/depot recorded this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_mortality', to='company.branch'),
        ),
    ]
