# Generated by Django 6.1.1 on 2026-09-24 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyjoinrequest_assigned_branch'),
        ('company', '0007_branch_parent'),
        ('kuku_biz', '0015_alter_birdsale_branch_alter_eggproduction_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this customer belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuku_customers', to='company.branch'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='kuku_biz_cu_company_8a3600_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_active'], name='kuku_biz_cu_company_ebc233_idx'),
        ),
    ]
