# Generated by Django 6.1.1 on 2026-10-03 17:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0015_tenantfeedback'),
        ('company', '0009_expense_paid_by_expense_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('refund', 'Refund — Pesa uliyomrudishia mteja'), ('return', 'Return — Bidhaa iliyorudishwa'), ('discount', 'Discount / Allowance — Punguzo ulilotoa'), ('writeoff', 'Write-off — Deni lililoshindikana kulipwa'), ('damage', 'Damage / Spoilage — Bidhaa iliyoharibika'), ('shrinkage', 'Shrinkage — Wizi / Upotevu wa stock')], max_length=20)),
                ('refund_type', models.CharField(blank=True, choices=[('product_replacement', 'Product Replacement'), ('amount_refunded', 'Amount Refunded')], help_text='Only for Refund / Return categories', max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_model', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Selling amount (for refunds/returns/discounts/writeoffs)', max_digits=15)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase cost (for damages/shrinkage)', max_digits=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Auto-generated on save', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_return_records', to='company.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_return_records', to='companies.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_return_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loss / Return Record',
                'verbose_name_plural': 'Loss / Return Records',
                'db_table': 'losses_loss_return',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'branch', 'created_at'], name='losses_loss_company_6e47b7_idx'), models.Index(fields=['company', 'category'], name='losses_loss_company_5f4e98_idx'), models.Index(fields=['reference'], name='losses_loss_referen_677a7e_idx')],
            },
        ),
    ]
