# Generated by Django 6.1.1 on 2026-10-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lossreturn',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to True by company admin / stock controller to lock the record.'),
        ),
        migrations.AddField(
            model_name='lossreturn',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Optional notes added during verification.'),
        ),
        migrations.AddField(
            model_name='lossreturn',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the record was verified.', null=True),
        ),
        migrations.AddField(
            model_name='lossreturn',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified and locked this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loss_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
