# Generated by Django 6.1.1 on 2026-10-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0019_sale_barcode_number_and_more'),
        ('losses', '0002_lossreturn_is_verified_lossreturn_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossreturn',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Sale this return/refund relates to (set via barcode scan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_return_records', to='epa_shop.sale'),
        ),
        migrations.AddField(
            model_name='lossreturn',
            name='sale_barcode',
            field=models.CharField(blank=True, help_text='Barcode of the linked sale (if scanned).', max_length=50),
        ),
    ]
