# Generated by Django 4.2.7 on 2026-08-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epa_shop', '0009_rename_epa_sales_company_sale_number_idx_epa_sales_company_34ecab_idx_and_more'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_id',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='epa_shop.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('company_manager', 'Company Manager'), ('company_cashier', 'Company Cashier'), ('company_agent', 'Company Agent'), ('company_staff', 'Company Staff')], default='company_staff', max_length=20),
        ),
    ]
