# Generated by Django 4.2.7 on 2026-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('company_manager', 'Company Manager'), ('company_cashier', 'Company Cashier'), ('stock_controller', 'Stock Controller'), ('company_agent', 'Company Agent'), ('mpesa_agent', 'Mpesa Agent'), ('company_staff', 'Company Staff')], default='company_staff', max_length=20),
        ),
    ]
