# Generated by Django 4.2.7 on 2026-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('email', 'Email'), ('url', 'URL'), ('image', 'Image'), ('file', 'File'), ('json', 'JSON')], default='text', max_length=20)),
                ('category', models.CharField(default='general', max_length=50)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['category', 'order', 'key'],
            },
        ),
    ]
