# Generated by Django 4.2.7 on 2026-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['category', 'order', 'key'], 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.RenameField(
            model_name='systemsetting',
            old_name='is_public',
            new_name='is_required',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('branding', 'Branding & Design'), ('email', 'Email Settings'), ('payment', 'Payment Settings'), ('currency', 'Currency & Localization'), ('language', 'Language & Internationalization'), ('security', 'Security'), ('preferences', 'Preferences'), ('integration', 'Integrations'), ('advanced', 'Advanced')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('email', 'Email'), ('url', 'URL'), ('image', 'Image'), ('color', 'Color'), ('password', 'Password'), ('select', 'Select'), ('file', 'File')], default='text', max_length=20),
        ),
        migrations.AlterModelTable(
            name='systemsetting',
            table=None,
        ),
    ]
