# Generated by Django 4.2.7 on 2026-09-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemsetting',
            table='system_settings',
        ),
    ]
