# Generated by Django 6.1.1 on 2026-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_systemsetting_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('branding', 'Branding'), ('email', 'Email'), ('payment', 'Payment'), ('preferences', 'Preferences')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('email', 'Email'), ('url', 'URL'), ('image', 'Image'), ('file', 'File'), ('color', 'Color'), ('password', 'Password'), ('select', 'Select')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
