# Generated by Django 6.1.1 on 2026-09-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_systemsetting_category_alter_systemsetting_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('email', 'Email'), ('url', 'URL'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('color', 'Color'), ('password', 'Password'), ('select', 'Select')], default='text', max_length=20),
        ),
    ]
