# Generated by Django 6.1.1 on 2026-10-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_systemsetting_setting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('user_message', models.TextField()),
                ('bot_reply', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_chat_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
