# Generated by Django 6.1.1 on 2026-10-10 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Geo Cache',
                'verbose_name_plural': 'IP Geo Cache',
                'db_table': 'analytics_ip_geo_cache',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('page', models.CharField(db_index=True, max_length=500)),
                ('full_path', models.CharField(blank=True, max_length=1000)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('referrer', models.CharField(blank=True, max_length=1000)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'analytics_visits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'page'], name='analytics_v_created_2aa803_idx'), models.Index(fields=['ip_address', 'created_at'], name='analytics_v_ip_addr_10e62d_idx'), models.Index(fields=['created_at', 'country'], name='analytics_v_created_f48652_idx')],
            },
        ),
    ]
