# Generated by Django 6.1.1 on 2026-10-10 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['read_at', 'created_at'], name='analytics_v_read_at_582429_idx'),
        ),
    ]
