# Generated by Django 4.2.7 on 2026-09-06 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epa_shop', '0013_phone_features_phone_memory_card_phone_network_type_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('PERSONAL_SAVINGS', '💰 Personal Savings'), ('MPESA_COMMISSION', '📱 M-Pesa Commission'), ('CREDIT_LOAN', '🏦 Credit/Loan'), ('INVESTOR', '👤 Investor'), ('OTHER', '📌 Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocation', models.CharField(choices=[('BANK', 'Bank Account'), ('MPESA', 'M-Pesa Float'), ('CASH', 'Cash'), ('SPLIT', 'Split Across Accounts')], default='MPESA', max_length=10)),
                ('bank_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mpesa_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mpesa_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mpesa_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boost Transaction',
                'verbose_name_plural': 'Boost Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('salary', 'Salary'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('supplies', 'Office Supplies'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('tax', 'Tax'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('m-pesa', 'M-Pesa'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Invoice or receipt number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='epa_shop.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'expense_date'], name='company_exp_company_53cc4a_idx'), models.Index(fields=['company', 'category'], name='company_exp_company_21d948_idx'), models.Index(fields=['company', 'status'], name='company_exp_company_3ba44e_idx'), models.Index(fields=['expense_date'], name='company_exp_expense_0cbcbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Record',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Balance'), ('MPESA', 'M-Pesa Float'), ('CASH', 'Cash Balance')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Float Account',
                'unique_together': {('user', 'account_type')},
            },
        ),
    ]
