# Generated by Django 4.2.7 on 2026-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload receipt or invoice (JPG, PNG, GIF, or PDF)', null=True, upload_to='expense_attachments/%Y/%m/'),
        ),
    ]
