# Generated by Django 4.2.7 on 2026-09-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_bank', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_mpesa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_all', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BANK', 'Bank Account'), ('MPESA', 'M-Pesa Account'), ('CASH', 'Cash Account'), ('CREDIT', 'Credit/Loan')], max_length=10)),
                ('name', models.CharField(help_text='e.g., Equity Bank, M-Pesa Merchant Line 1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('user', 'category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('MPESA_MERCHANT', 'M-Pesa Merchant Line'), ('MPESA_TILL', 'M-Pesa Till Number'), ('MPESA_PAYBILL', 'M-Pesa Paybill'), ('MPESA_OTHER', 'M-Pesa Other'), ('BANK_CURRENT', 'Current Account'), ('BANK_SAVINGS', 'Savings Account'), ('BANK_FIXED', 'Fixed Deposit'), ('BANK_OTHER', 'Other Bank Account'), ('CASH_MAIN', 'Main Cash'), ('CASH_PETTY', 'Petty Cash'), ('CASH_OTHER', 'Other Cash'), ('CREDIT_LOAN', 'Loan Account'), ('CREDIT_OVERDRAFT', 'Overdraft'), ('CREDIT_OTHER', 'Other Credit')], max_length=20)),
                ('name', models.CharField(help_text='e.g., Merchant Line 1, KCB Main Account', max_length=200)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number or M-Pesa number', max_length=100)),
                ('till_number', models.CharField(blank=True, help_text='M-Pesa till/paybill number', max_length=50)),
                ('merchant_name', models.CharField(blank=True, help_text='M-Pesa merchant name', max_length=200)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='company.accounttype')),
            ],
            options={
                'ordering': ['account_type__category', 'name'],
                'unique_together': {('account_type', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='bank_balance',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='mpesa_balance',
        ),
        migrations.AddField(
            model_name='boosttransaction',
            name='allocations',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary of sub-account allocations: {'sub_account_id': amount, ...}"),
        ),
        migrations.AddField(
            model_name='boosttransaction',
            name='sub_account_after',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='boosttransaction',
            name='sub_account_before',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='sub_account_balances',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary of sub-account balances: {'sub_account_id': balance, ...}"),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='total_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='total_mpesa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
