# Generated by Django 4.2.7 on 2026-09-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_accountsummary_accounttype_subaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='store_number',
            field=models.CharField(blank=True, help_text='M-Pesa store number', max_length=50),
        ),
    ]
