# Generated by Django 4.2.7 on 2026-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_expense_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='bill_period',
            field=models.DateField(blank=True, help_text='Billing period (use 1st of month)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('phone', 'Phone'), ('security', 'Security'), ('waste', 'Waste Collection'), ('other', 'Other Bill')], max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('rent', 'Rent'), ('bill', 'Bill'), ('general', 'General Expense')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='landlord_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number for rent/bills', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='rent_month',
            field=models.DateField(blank=True, help_text='Month the rent is for (use 1st of month)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='salary_month',
            field=models.DateField(blank=True, help_text='Month the salary is for (use 1st of month)', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('transport', 'Transport'), ('utilities', 'Utilities'), ('supplies', 'Office Supplies'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('tax', 'Tax'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_type', 'expense_date'], name='company_exp_company_62cae8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_type', 'status'], name='company_exp_company_471663_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'salary_month'], name='company_exp_company_625bba_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'rent_month'], name='company_exp_company_8b313a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'bill_period'], name='company_exp_company_0c36b9_idx'),
        ),
    ]