# Generated by Django 4.2.7 on 2026-09-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_expense_company_exp_company_53cc4a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_company_53cc4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_company_21d948_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_company_3ba44e_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_expense_0cbcbe_idx',
        ),
    ]
