# Generated by Django 4.2.7 on 2026-09-06 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('epa_shop', '0013_phone_features_phone_memory_card_phone_network_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_subaccount_store_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='boosttransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='epa_shop.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounttype',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounttype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boosttransaction',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boost_transactions', to='epa_shop.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boosttransaction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boost_transactions', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boosttransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='epa_shop.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='epa_shop.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subaccount',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('company', 'branch', 'category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('branch', 'date')},
        ),
        migrations.DeleteModel(
            name='AccountSummary',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='user',
        ),
    ]
