# Generated by Django 6.1.1 on 2026-09-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_businesstype_name'),
        ('company', '0004_remove_expense_company_exp_company_53cc4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, help_text='Cloudinary public_id for the receipt/invoice (JPG, PNG, GIF, or PDF)', max_length=500, null=True, upload_to='expense_attachments/%Y/%m/'),
        ),
        # Branch was moved here from epa_shop. The physical table
        # ("epa_branches") already exists with data, so we only update
        # Django's state — we do NOT recreate the table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Branch',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('code', models.CharField(max_length=20, unique=True)),
                        ('address', models.TextField()),
                        ('city', models.CharField(blank=True, max_length=100)),
                        ('country', models.CharField(blank=True, max_length=100)),
                        ('phone', models.CharField(max_length=20)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('currency', models.CharField(default='KES', help_text='Currency code (KES, USD, EUR, etc.)', max_length=10)),
                        ('currency_symbol', models.CharField(default='KSh', help_text='Currency symbol (KSh, $, €, etc.)', max_length=10)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_branches', to='companies.company')),
                        ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'epa_branches',
                        'ordering': ['name'],
                        'unique_together': {('company', 'code')},
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='company.branch'),
        ),
    ]