# Generated by Django 4.2.7 on 2026-09-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_accounttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boosttransaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_company_53cc4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_company_21d948_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_company_3ba44e_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='company_exp_expense_0cbcbe_idx',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='boosttransaction',
            name='allocations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='sub_account_balances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='store_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='till_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
