# Generated by Django 6.1.1 on 2026-09-24 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyjoinrequest_assigned_branch'),
        ('company', '0005_alter_expense_attachment_branch_alter_expense_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_mother_branch',
            field=models.BooleanField(default=False, help_text='Marks this branch as the HQ/feeder for the company.'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_mother_branch', True)), fields=('company',), name='one_mother_branch_per_company'),
        ),
    ]
