# Generated by Django 6.1.1 on 2026-09-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_branch_is_mother_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Mother branch this branch belongs to (blank for mother/HQ).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='company.branch'),
        ),
    ]
