# Generated by Django 6.1.1 on 2026-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_branch_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment_format',
            field=models.CharField(blank=True, default='', help_text='Cloudinary format (pdf, jpg, png, ...). Set at upload time.', max_length=10),
        ),
    ]
